# Generated by Django 5.0.8 on 2026-05-08 09:48

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RenameIndex(
            model_name='department',
            new_name='accounts_de_code_14a6a8_idx',
            old_name='accounts_de_code_17ac2e_idx',
        ),
        migrations.RenameIndex(
            model_name='user',
            new_name='accounts_us_role_9fc6ca_idx',
            old_name='accounts_us_role_71cf4b_idx',
        ),
        migrations.RenameIndex(
            model_name='user',
            new_name='accounts_us_departm_993fcb_idx',
            old_name='accounts_us_depart_2dac47_idx',
        ),
        migrations.RenameIndex(
            model_name='user',
            new_name='accounts_us_employe_0cbd94_idx',
            old_name='accounts_us_employe_93be6d_idx',
        ),
        migrations.RenameIndex(
            model_name='userloginaudit',
            new_name='accounts_us_ip_addr_cfeaed_idx',
            old_name='accounts_us_ip_addr_594d4e_idx',
        ),
        migrations.RenameIndex(
            model_name='userloginaudit',
            new_name='accounts_us_success_92fd0c_idx',
            old_name='accounts_us_success_b95474_idx',
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
