# Generated by Django 5.0.8 on 2026-05-08 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='performancelog',
            new_name='reports_per_user_id_da0c73_idx',
            old_name='reports_per_user_id_d6c688_idx',
        ),
        migrations.RenameIndex(
            model_name='performancelog',
            new_name='reports_per_product_47fa1c_idx',
            old_name='reports_per_product_b1c923_idx',
        ),
    ]
