# Generated by Django 5.0.8 on 2026-05-08 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='task',
            new_name='tasks_task_assigne_b3b2bc_idx',
            old_name='tasks_task_assigne_5a2321_idx',
        ),
        migrations.RenameIndex(
            model_name='task',
            new_name='tasks_task_due_dat_3f7773_idx',
            old_name='tasks_task_due_dat_47924e_idx',
        ),
        migrations.RenameIndex(
            model_name='task',
            new_name='tasks_task_priorit_685c61_idx',
            old_name='tasks_task_priorit_5126f6_idx',
        ),
    ]
