# Generated by Django 5.0.8 on 2026-05-08 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='leaverequest',
            new_name='leaves_leav_user_id_afb901_idx',
            old_name='leaves_leav_user_id_cc28f0_idx',
        ),
        migrations.RenameIndex(
            model_name='leaverequest',
            new_name='leaves_leav_start_d_96457d_idx',
            old_name='leaves_leav_start_d_1e2fd0_idx',
        ),
    ]
