# Generated by Django 5.0.8 on 2026-05-08 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_notific_f2e0f7_idx',
            old_name='notificatio_notific_b107a5_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_is_glob_ac74e4_idx',
            old_name='notificatio_is_glob_ccbcf5_idx',
        ),
    ]
