# Generated by Django 5.0.8 on 2026-05-08 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='attendance',
            new_name='attendance__date_3889e6_idx',
            old_name='attendance__date_6daf1a_idx',
        ),
        migrations.RenameIndex(
            model_name='attendance',
            new_name='attendance__user_id_c01e0c_idx',
            old_name='attendance__user_id_7d98b8_idx',
        ),
        migrations.RenameIndex(
            model_name='attendance',
            new_name='attendance__punch_i_3369b4_idx',
            old_name='attendance__punch_i_5fab25_idx',
        ),
        migrations.RenameIndex(
            model_name='attendanceattempt',
            new_name='attendance__user_id_85c230_idx',
            old_name='attendance__user_id_514ed0_idx',
        ),
        migrations.RenameIndex(
            model_name='attendanceattempt',
            new_name='attendance__allowed_18c853_idx',
            old_name='attendance__allowed_d218a1_idx',
        ),
        migrations.RenameIndex(
            model_name='officelocation',
            new_name='attendance__is_acti_99dff5_idx',
            old_name='attendance__is_acti_519b7d_idx',
        ),
    ]
